# Serveur
server.port=8080

# H2 Database (pas besoin d'installer PostgreSQL)
spring.datasource.url=jdbc:h2:mem:eventhub
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console H2 (pour voir la BDD dans le navigateur)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
jwt.secret=eventhubSecretKey2026ForJWTTokenGeneration123456
jwt.expiration=86400000

# Logging
logging.level.com.eventhub=DEBUG
logging.level.org.springframework.security=DEBUG