apiVersion: v1
kind: Secret
metadata:
  name: eventhub-secrets
  namespace: eventhub
type: Opaque
stringData:
  mysql-root-password: rootpassword
  jwt-secret: eventhub-super-secret-jwt-key-2024-XXXXXXXXXXXXXXXXXXXXXXXXXX
