apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-uploads-pvc
  namespace: eventhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: eventhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
        - name: event-service
          image: anaselmidaoui/event-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-server:3306/db_event?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventhub-secrets
                  key: mysql-root-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eventhub-secrets
                  key: jwt-secret
            - name: UPLOAD_DIR
              value: "/app/uploads"
            - name: UPLOAD_BASE_URL
              value: "http://localhost:8000"
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: event-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: eventhub
spec:
  selector:
    app: event-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
